import { loadAmap, type AMapPoi } from "./amap-loader";
import { resolveAmapRoute } from "./amap-route-service";
import type { Place, RoutePoint, RouteSegment } from "./types";

export interface FoodCandidate { poiId:string; name:string; address:string; longitude:number; latitude:number; category?:string; rating?:number; cost?:string; detourMinutes?:number; }
const cache=new Map<string,FoodCandidate[]>();
const key=(s:RouteSegment)=>`${s.fromPlaceId}:${s.toPlaceId}:${s.path.map(p=>`${p.lng.toFixed(4)},${p.lat.toFixed(4)}`).join(";")}`;
const distance=(a:RoutePoint,b:RoutePoint)=>Math.hypot((a.lng-b.lng)*85000,(a.lat-b.lat)*111000);
function anchors(path:RoutePoint[],minutes:number){const fractions=minutes>45?[.25,.5,.75]:minutes>25?[1/3,2/3]:[.5];return fractions.map(f=>path[Math.max(1,Math.min(path.length-2,Math.round((path.length-1)*f)))]).filter(Boolean);}
function poi(poi:AMapPoi):FoodCandidate|undefined{const longitude=Number(poi.location?.lng),latitude=Number(poi.location?.lat);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))return;const rating=Number(poi.biz_ext?.rating??poi.rating);return {poiId:poi.id,name:poi.name,address:poi.address||"暂无详细地址",longitude,latitude,category:poi.type,rating:Number.isFinite(rating)?rating:undefined,cost:poi.biz_ext?.cost};}
export async function precheckAlongRouteFood(segment:RouteSegment,city:string):Promise<FoodCandidate[]>{if(segment.durationMinutes===null||segment.durationMinutes<15||segment.path.length<3)return [];const k=key(segment);if(cache.has(k))return cache.get(k)!;const AMap=await loadAmap(),found:FoodCandidate[]=[];for(const anchor of anchors(segment.path,segment.durationMinutes)){const list=await new Promise<FoodCandidate[]>((resolve)=>new AMap.PlaceSearch({city,citylimit:true,pageSize:8}).searchNearBy("餐饮",[anchor.lng,anchor.lat],600,(status,result)=>resolve(status==="complete"?(result.poiList?.pois??[]).map(poi).filter((p):p is FoodCandidate=>Boolean(p)):[])));found.push(...list);}const unique=[...new Map(found.map(item=>[item.poiId,item])).values()].filter(item=>Math.min(...segment.path.map(point=>distance(point,{lng:item.longitude,lat:item.latitude})))<=500);cache.set(k,unique);return unique;}
export async function rankAlongRouteFood(segment:RouteSegment,from:Place,to:Place,city:string):Promise<FoodCandidate[]>{const candidates=await precheckAlongRouteFood(segment,city);const scored=await Promise.all(candidates.slice(0,6).map(async candidate=>{const p:Place={id:`food-${candidate.poiId}`,rawName:candidate.name,name:candidate.name,poiStatus:"resolved",poiId:candidate.poiId,address:candidate.address,longitude:candidate.longitude,latitude:candidate.latitude,type:"food",category:candidate.category,tips:[],evidence:[],estimatedDurationMinutes:60,durationSource:"default",recommendationScore:3,mustVisit:false};const [a,b]=await Promise.all([resolveAmapRoute(from,p,"transit",city),resolveAmapRoute(p,to,"transit",city)]);if(a.durationMinutes===null||b.durationMinutes===null||segment.durationMinutes===null)return candidate;return {...candidate,detourMinutes:Math.max(0,a.durationMinutes+b.durationMinutes-segment.durationMinutes)};}));return scored.filter(item=>item.detourMinutes!==undefined).sort((a,b)=>a.detourMinutes!-b.detourMinutes!||(b.rating??0)-(a.rating??0)).slice(0,3);}
