import "./style.css";
import { extractPlaces, type ImageInput } from "./ai-extraction";
import { MapView } from "./map-view";
import { resolvePlace } from "./poi-resolver";
import { dedupeResolvedPlaces } from "./poi-dedup";
import { resolveAmapRoute } from "./amap-route-service";
import { groupPlaces } from "./day-grouping";
import { planRoutes } from "./route-planning";
import type { DayRoute, Place, PoiCandidate, PlanningResult, ResolvedPlace, RoutePlanningResult, TripPreferences } from "./types";

const SAMPLE = "周末准备去上海玩两天。第一天上午先去武康大楼，然后沿武康路走到安福路，中午随便找地方吃饭。如果不累的话下午去上生新所。第二天上午想去豫园，下午慢慢逛到外滩，晚上就在外滩看夜景。";
const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("找不到应用根节点");
app.innerHTML = `<main class="app-shell"><aside class="panel"><p class="eyebrow">TRAVEL NOTES TO MAP</p><h1>攻略上图</h1><p class="intro">把收藏的攻略，摊到真实地图上。</p><section class="input-panel"><div id="input-summary" class="input-summary" hidden><span id="input-summary-text"></span><button id="edit-input" class="secondary-button" type="button">展开</button></div><div id="input-area"><label class="field city-field" for="city"><span>城市</span><input id="city" value="上海" aria-label="城市" /></label><label class="label" for="notes">攻略文本</label><textarea id="notes" rows="8" aria-label="攻略文本">${SAMPLE}</textarea><label class="upload" for="images"><span>上传攻略截图（最多 6 张）</span><strong>选择图片</strong><input id="images" type="file" accept="image/png,image/jpeg,image/webp" multiple /></label><div id="previews" class="previews"></div></div></section><button id="extract-button" class="primary-button" type="button">帮我上图</button><p id="status" class="status" role="status">正在加载高德地图……</p><section id="places-section" aria-label="地点列表" hidden><div class="trip-controls"><strong>你想怎么玩？</strong><select id="trip-days"><option value="auto">随便</option><option value="1">1天</option><option value="2">2天1晚</option><option value="3">3天2晚</option><option value="4">4天3晚</option><option value="5">5天4晚</option></select><select id="pace"><option value="vacation">度假</option><option value="relaxed">轻松</option><option value="flexible" selected>随便</option><option value="compact">紧凑</option><option value="intense">特种兵</option></select><button id="plan-days" type="button">生成路线安排</button></div><div id="day-groups"></div><p id="places-title" class="label">地点</p><div class="decision-toolbar"><div id="filters"><button data-filter="0">全部</button><button data-filter="5">5星</button><button data-filter="4">4星+</button><button data-filter="3">3星+</button></div><button id="remove-low">去掉三星以下</button></div><ul id="place-list" class="place-list"></ul></section></aside><section class="map-panel" aria-label="高德地图"><div id="map" class="map"></div><div id="map-message" class="map-message" hidden></div></section></main>`;
const mapView = new MapView(), mapContainer = document.querySelector<HTMLElement>("#map")!;
const cityInput = document.querySelector<HTMLInputElement>("#city")!, notesInput = document.querySelector<HTMLTextAreaElement>("#notes")!, button = document.querySelector<HTMLButtonElement>("#extract-button")!, planButton = document.querySelector<HTMLButtonElement>("#plan-days")!, status = document.querySelector<HTMLParagraphElement>("#status")!, section = document.querySelector<HTMLElement>("#places-section")!, title = document.querySelector<HTMLParagraphElement>("#places-title")!, list = document.querySelector<HTMLUListElement>("#place-list")!, mapMessage = document.querySelector<HTMLDivElement>("#map-message")!, inputArea = document.querySelector<HTMLElement>("#input-area")!, imageInput = document.querySelector<HTMLInputElement>("#images")!, previews = document.querySelector<HTMLElement>("#previews")!, editInput = document.querySelector<HTMLButtonElement>("#edit-input")!, inputSummary = document.querySelector<HTMLElement>("#input-summary")!, inputSummaryText = document.querySelector<HTMLElement>("#input-summary-text")!;
let mapReady = false, places: Place[] = [], images: ImageInput[] = [], scoreFilter = 0, planningCity = "";
const selectedImageKeys = new Set<string>();
let planningResult: PlanningResult | undefined, routePlanningResult: RoutePlanningResult | undefined;
const setStatus = (message: string, error = false) => { status.textContent = message; status.className = `status ${error ? "is-error" : ""}`; };
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
const toResolved = (place: Place): ResolvedPlace | undefined => place.poiStatus === "resolved" && place.poiId && place.name && place.address && place.longitude !== undefined && place.latitude !== undefined ? { status: "resolved", poiId: place.poiId, name: place.name, address: place.address, longitude: place.longitude, latitude: place.latitude, category: place.category, tips: place.tips, type: place.type } : undefined;
function refreshMap(): void { const resolved = places.map(toResolved).filter((item): item is ResolvedPlace => Boolean(item)); if (mapReady) mapView.showPlaces(resolved, routePlanningResult?.days ?? []); }
function invalidatePlans(): void { planningResult = undefined; routePlanningResult = undefined; document.querySelector<HTMLElement>("#day-groups")!.innerHTML = ""; refreshMap(); }
function candidateMeta(candidate: PoiCandidate): string { return [candidate.address, candidate.poiType].filter(Boolean).join(" · ") || "暂无详细信息"; }
function displayType(type?: Place["type"], category?: string): string { return ({ attraction: "景点", food: "餐饮", hotel: "住宿", transport: "交通", other: "其他" })[type ?? "other"] ?? category ?? "其他"; }
function typeIcon(type?: Place["type"]): string { return ({ attraction: "🎡", food: "🍜", hotel: "🏨", transport: "🚄", other: "📍" })[type ?? "other"]; }
function durationOptions(value?: number | null): string { return [[30,"30m"],[60,"1h"],[90,"1.5h"],[120,"2h"],[180,"3h"],[240,"4h"],[480,"全天"]].map(([n,label]) => `<option value="${n}" ${value === n ? "selected" : ""}>${label}</option>`).join(""); }
const placeName = (id: string) => places.find((place) => place.id === id)?.rawName ?? "地点";
const formatMinutes = (minutes: number | null) => minutes === null ? "路线获取失败" : minutes < 60 ? `${minutes}min` : `${Math.floor(minutes / 60)}h${minutes % 60 ? `${minutes % 60}min` : ""}`;
function renderDayRoute(day: DayRoute): string { const rows = day.orderedPlaceIds.map((id, index) => `${index ? `<div class="route-leg">↓ ${day.segments[index - 1]?.status === "failed" ? "路线获取失败" : `${day.segments[index - 1]?.transportMode === "walking" ? "步行" : "公交 / 地铁"} ${formatMinutes(day.segments[index - 1]?.durationMinutes ?? null)}`}</div>` : ""}<div class="route-stop">${escapeHtml(placeName(id))}</div>`).join(""); const total = day.totalTransitMinutes === null ? "通勤：部分路线获取失败" : `通勤：${formatMinutes(day.totalTransitMinutes)}`; return `<div class="day-card"><strong>Day ${day.day} · ${day.orderedPlaceIds.length} 个地点</strong><div class="route-stops">${rows}</div><small>游玩：${formatMinutes(day.totalActivityMinutes)} · ${total}</small>${day.warnings.map((warning) => `<small class="warning">⚠️ ${escapeHtml(warning)}</small>`).join("")}</div>`; }
function renderRoutes(): string { if (!planningResult) return ""; if (!routePlanningResult) return `<p class="route-stale">路线安排已失效，请重新生成。</p>`; return `${planningResult.inferredDays ? `<p>建议 ${planningResult.inferredDays} 天</p>` : ""}${routePlanningResult.days.map(renderDayRoute).join("")}${[...planningResult.warnings, ...routePlanningResult.warnings].map((warning) => `<p class="warning">⚠️ ${escapeHtml(warning)}</p>`).join("")}`; }
function renderPlaces(): void {
  section.hidden = places.length === 0; title.textContent = `找到了 ${places.length} 个地点`; document.querySelector<HTMLElement>("#day-groups")!.innerHTML = renderRoutes();
  const labels: Record<Place["poiStatus"], string> = { resolved: "✓ 已定位", ambiguous: "? 需要确认", not_found: "! 未找到", failed: "× 搜索失败", unresolved: "待确认" };
  const visible = places.map((place, index) => ({ place, index })).filter(({ place }) => place.recommendationScore >= scoreFilter).sort((a,b) => b.place.recommendationScore - a.place.recommendationScore || a.index - b.index);
  list.innerHTML = visible.map(({ place }) => `<li class="place-card"><div class="place-card-header"><div class="place-title"><span class="place-name">${typeIcon(place.type)} ${escapeHtml(place.rawName)}</span><span class="type-badge">${escapeHtml(displayType(place.type, place.category))}</span></div><div class="place-actions"><span class="state state-${place.poiStatus}">${labels[place.poiStatus]}</span><button class="delete" data-delete="${place.id}" type="button">删除</button></div></div><div class="score-row"><strong>${"★".repeat(place.recommendationScore)}${"☆".repeat(5-place.recommendationScore)}</strong><span>种草指数 · 来自导入攻略</span></div><p class="reason">${escapeHtml(place.recommendationReason ?? "攻略未表达明显倾向")}</p><div class="place-meta"><label>预计停留 <select data-duration="${place.id}">${durationOptions(place.estimatedDurationMinutes)}</select></label><button class="must-visit ${place.mustVisit ? "active" : ""}" data-must="${place.id}">${place.mustVisit ? "♥ 必去" : "♡ 设为必去"}</button></div>${place.tips?.length ? `<p class="tips">攻略提示：${place.tips.map(escapeHtml).join("；")}</p>` : ""}${place.poiStatus === "ambiguous" && (place.poiCandidates?.length ?? 0) ? `<div class="candidates"><p>你想去的是：</p>${(place.poiCandidates ?? []).map((candidate, index) => `<button type="button" class="candidate" data-place="${place.id}" data-candidate="${index}"><strong>${escapeHtml(candidate.name)}</strong><span>${escapeHtml(candidateMeta(candidate))}</span></button>`).join("")}<button type="button" class="skip-candidate" data-skip="${place.id}">暂时跳过</button></div>` : ""}</li>`).join("");
  list.querySelectorAll<HTMLButtonElement>(".candidate").forEach((item) => item.addEventListener("click", () => chooseCandidate(item.dataset.place!, Number(item.dataset.candidate))));
  list.querySelectorAll<HTMLButtonElement>(".delete").forEach((item) => item.addEventListener("click", () => { places = places.filter((place) => place.id !== item.dataset.delete); invalidatePlans(); renderPlaces(); refreshMap(); }));
  list.querySelectorAll<HTMLSelectElement>("select[data-duration]").forEach((item) => item.addEventListener("change", () => { const place = places.find((entry) => entry.id === item.dataset.duration); if (place) { place.estimatedDurationMinutes = item.value ? Number(item.value) : null; place.durationEdited = true; invalidatePlans(); renderPlaces(); } }));
  list.querySelectorAll<HTMLButtonElement>(".skip-candidate").forEach((item) => item.addEventListener("click", () => { const place = places.find((entry) => entry.id === item.dataset.skip); if (place) { place.poiCandidates = []; renderPlaces(); } }));
  list.querySelectorAll<HTMLButtonElement>(".must-visit").forEach((item) => item.addEventListener("click", () => { const place = places.find((entry) => entry.id === item.dataset.must); if (place) { place.mustVisit = !place.mustVisit; invalidatePlans(); renderPlaces(); } }));
}
function applyDedupe(): void { const deduped = dedupeResolvedPlaces(places); places = deduped.places; if (deduped.warnings.length) console.warn("POI dedupe warnings:", deduped.warnings); }
function chooseCandidate(id: string, index: number): void { const place = places.find((entry) => entry.id === id), candidate = place?.poiCandidates?.[index]; if (!place || !candidate) return; Object.assign(place, candidate, { poiStatus: "resolved" }); applyDedupe(); invalidatePlans(); renderPlaces(); refreshMap(); setStatus(`${place.rawName} 已确认并添加到地图。`); }
async function groundPlaces(city: string): Promise<void> { setStatus("正在确认地点……"); const results = await Promise.all(places.map(async (place) => ({ place, result: await resolvePlace({ city, name: place.rawName }) }))); places = results.map(({ place, result }) => result.status === "resolved" ? { ...place, ...result, poiStatus: "resolved" } : result.status === "ambiguous" ? { ...place, poiStatus: "ambiguous", poiCandidates: result.candidates } : { ...place, poiStatus: result.status }); applyDedupe(); renderPlaces(); refreshMap(); const confirmed = places.filter((place) => place.poiStatus === "resolved").length; setStatus(confirmed ? `${confirmed} 个地点已确认；其余地点可在列表中继续确认。` : "暂无可自动确认的地点，请查看候选结果。", confirmed === 0); }
async function extractAndShow(): Promise<void> { if (!mapReady) return; const text = notesInput.value.trim(), manualCity = cityInput.value.trim(); if (!text && !images.length) { setStatus("请粘贴攻略文本或上传至少一张截图。", true); return; } button.disabled = true; try { setStatus("正在从攻略里找你种草的地方……"); const extraction = await extractPlaces(text, images), city = manualCity || extraction.city; if (!city) { setStatus("未能判断城市，请先填写城市后再试。", true); return; } planningCity = city; if (!manualCity && extraction.city) cityInput.value = extraction.city; places = extraction.places.map((place, index) => ({ id: `${place.name}-${index}`, rawName: place.name, poiStatus: "unresolved", mustVisit: false, ...place })); invalidatePlans(); setInputCollapsed(true); if (!places.length) { renderPlaces(); refreshMap(); setStatus("没有找到明确的可前往地点。", true); return; } await groundPlaces(city); } catch (error) { setStatus(error instanceof Error ? error.message : "攻略解析失败，请稍后重试。", true); } finally { button.disabled = false; } }
function preferences(): TripPreferences { const raw = document.querySelector<HTMLSelectElement>("#trip-days")!.value, pace = document.querySelector<HTMLSelectElement>("#pace")!.value as TripPreferences["pace"]; return { tripDays: raw === "auto" ? null : Number(raw), tripNights: raw === "auto" ? null : Math.max(0, Number(raw) - 1), durationMode: raw === "auto" ? "auto" : "user_selected", pace }; }
async function createPlan(): Promise<void> { if (!planningCity) { setStatus("缺少已确认的目的地城市，无法获取真实路线。", true); return; } planButton.disabled = true; try { planningResult = groupPlaces(places, preferences()); routePlanningResult = undefined; renderPlaces(); refreshMap(); setStatus("正在通过高德确认日内路线……"); routePlanningResult = await planRoutes(planningResult.groups, places, planningCity, resolveAmapRoute); renderPlaces(); refreshMap(); setStatus(routePlanningResult.warnings.length ? "路线已生成，部分路段未能获取。" : "已生成真实高德路线。"); } catch (error) { routePlanningResult = undefined; renderPlaces(); refreshMap(); setStatus(error instanceof Error ? error.message : "路线规划失败，请稍后重试。", true); } finally { planButton.disabled = false; } }
button.addEventListener("click", () => void extractAndShow()); planButton.addEventListener("click", () => void createPlan()); document.querySelectorAll<HTMLButtonElement>("[data-filter]").forEach((item) => item.addEventListener("click", () => { scoreFilter = Number(item.dataset.filter); renderPlaces(); }));
document.querySelector<HTMLButtonElement>("#remove-low")!.addEventListener("click", () => { const removed = places.filter((place) => place.recommendationScore < 3 && !place.mustVisit); places = places.filter((place) => place.recommendationScore >= 3 || place.mustVisit); invalidatePlans(); renderPlaces(); refreshMap(); setStatus(`已移除 ${removed.length} 个低优先级地点。`); });
document.querySelectorAll<HTMLSelectElement>("#trip-days, #pace").forEach((item) => item.addEventListener("change", () => { invalidatePlans(); renderPlaces(); })); editInput.addEventListener("click", () => setInputCollapsed(!inputArea.hidden));
imageInput.addEventListener("change", async () => { const files = [...(imageInput.files ?? [])]; const additions = files.filter((file) => !selectedImageKeys.has(`${file.name}-${file.size}-${file.lastModified}`)); if (images.length + additions.length > 6 || additions.some((file) => file.size > 5 * 1024 * 1024)) { setStatus("最多上传 6 张图片，单张不超过 5MB。", true); imageInput.value = ""; return; } const converted = await Promise.all(additions.map((file) => new Promise<ImageInput>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ mimeType: file.type, data: String(reader.result).split(",")[1] }); reader.onerror = () => reject(new Error(`无法读取图片：${file.name}`)); reader.readAsDataURL(file); }))); additions.forEach((file) => selectedImageKeys.add(`${file.name}-${file.size}-${file.lastModified}`)); images = [...images, ...converted]; imageInput.value = ""; previews.textContent = images.length ? `已选择 ${images.length} 张攻略截图，可继续选择追加。` : ""; });
function setInputCollapsed(collapsed: boolean): void { inputArea.hidden = collapsed; inputSummary.hidden = !collapsed; if (collapsed) { const parts = []; if (notesInput.value.trim()) parts.push(`📄 已解析攻略 · ${notesInput.value.trim().length} 字`); if (images.length) parts.push(`📷 ${images.length} 张攻略截图`); inputSummaryText.textContent = parts.join(" + "); editInput.textContent = "展开"; } else editInput.textContent = "收起"; }
void mapView.mount(mapContainer).then(() => { mapReady = true; setStatus("地图已加载，粘贴攻略后即可上图。"); }).catch((error: unknown) => { const message = error instanceof Error ? error.message : "高德地图 SDK 加载失败"; mapMessage.textContent = message; mapMessage.hidden = false; setStatus(message, true); button.disabled = true; });
