import "./style.css";
import { extractPlaces, type ImageInput } from "./ai-extraction";
import { MapView } from "./map-view";
import { resolvePlace, searchPoiCandidates } from "./poi-resolver";
import { dedupeResolvedPlaces } from "./poi-dedup";
import { resolveAmapRoute } from "./amap-route-service";
import { groupPlaces } from "./day-grouping";
import { planRoutes, rebuildManualDay } from "./route-planning";
import { summarizePlaceGuides } from "./place-guide-summary";
import { getPlaceVisual, placeTypeFromVisual, placeVisualIcon } from "./place-visual";
import { precheckAlongRouteFood, rankAlongRouteFood, type FoodCandidate } from "./along-route-food";
import { findHotelsNearStayArea, recommendStayAreas } from "./stay-recommendations";
import type { DayRoute, Pace, Place, PlaceGuideSummary, PoiCandidate, PlanningResult, ResolvedPlace, RoutePlanningResult, StayAreaCandidate, StayHotelCandidate, StayRecommendationState, TripPreferences } from "./types";

const SAMPLE="周末准备去上海玩两天。第一天上午先去武康大楼，然后沿武康路走到安福路。如果不累的话下午去上生新所。第二天上午想去豫园，下午慢慢逛到外滩。";
const app=document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML=`<main class="app-shell">
  <aside class="panel"><p class="eyebrow">TRAVEL NOTES TO MAP</p><h1>攻略上图</h1><p class="intro">把收藏的攻略，摊到真实地图上。</p>
    <section class="input-panel"><div id="input-summary" class="input-summary" hidden><span id="input-summary-text"></span><button id="edit-input" class="secondary-button">展开原始输入</button></div><div id="input-area"><label class="field city-field"><span>城市</span><input id="city" value="上海" aria-label="城市" /></label><label class="label" for="notes">攻略文本</label><textarea id="notes" rows="7" aria-label="攻略文本">${SAMPLE}</textarea><label class="upload" for="images"><span>上传攻略截图（最多 6 张）</span><strong>选择图片</strong><input id="images" type="file" accept="image/png,image/jpeg,image/webp" multiple /></label><div id="previews" class="previews"></div></div></section>
    <button id="extract-button" class="primary-button">帮我上图</button><p id="status" class="status" role="status">正在加载高德地图……</p>
    <section id="workspace" hidden><section id="settings" class="settings-card"></section><nav class="tabs"><button id="tab-places">地点 <span id="place-count">0</span></button><button id="tab-itinerary">行程 <span id="day-count">—</span></button></nav>
      <section id="places-view"><div class="decision-toolbar"><div id="filters"><button data-filter="0">全部</button><button data-filter="5">5星</button><button data-filter="4">4星+</button><button data-filter="3">3星+</button></div><div class="toolbar-actions"><button id="remove-low">去掉三星以下</button><button id="add-place-from-list" class="add-place-button">+ 添加地点</button></div></div><div id="place-manual-search"></div><ul id="place-list" class="place-list"></ul></section>
      <section id="itinerary-view" hidden></section>
    </section>
  </aside><section class="map-panel"><div id="map" class="map"></div><div id="map-message" class="map-message" hidden></div></section>
</main>`;
const $=<T extends Element>(s:string|T):T=>typeof s==="string"?document.querySelector<T>(s)!:s;
const mapView=new MapView(), city=$<HTMLInputElement>("#city"), notes=$<HTMLTextAreaElement>("#notes"), imageInput=$<HTMLInputElement>("#images"), status=$<HTMLParagraphElement>("#status"), workspace=$<HTMLElement>("#workspace"), list=$<HTMLUListElement>("#place-list"), settings=$<HTMLElement>("#settings"), itinerary=$<HTMLElement>("#itinerary-view"), inputArea=$<HTMLElement>("#input-area"), inputSummary=$<HTMLElement>("#input-summary"), inputSummaryText=$<HTMLElement>("#input-summary-text"), previews=$<HTMLElement>("#previews");
let mapReady=false, places:Place[]=[], images:ImageInput[]=[], planningCity="", planningResult:PlanningResult|undefined, routePlanningResult:RoutePlanningResult|undefined, scoreFilter=0, activeTab:"places"|"itinerary"="places", settingsExpanded=true, selectedDay:number|undefined, selectedPlaceId:string|undefined, routeStale=false, placeGuideSummaries=new Map<string,PlaceGuideSummary>(), guideSummaryState:"idle"|"loading"|"ready"|"failed"="idle", guideSummaryStale=true, unassignedPlaceIds:string[]=[], manualSearchResults:PoiCandidate[]=[], manualSearchOpen=false, manualSearchLoading=false, stayState:StayRecommendationState={status:"idle",areas:[],stale:false}, selectedStayAreaId:string|undefined, selectedHotel:Place|undefined;
const imageKeys=new Set<string>(); const esc=(x:string)=>x.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]!); const msg=(x:string,b=false)=>{status.textContent=x;status.className=`status ${b?"is-error":""}`};
const typeLabel=(t?:Place["type"])=>({attraction:"景点",food:"餐饮",hotel:"住宿",transport:"交通",other:"其他"})[t??"other"];
const typeIcon=(type?:Place["type"],category?:string)=>placeVisualIcon[getPlaceVisual({type,category})];
const mins=(n:number|null)=>n===null?"路线暂未获取":n<60?`${n}min`:`${Math.floor(n/60)}h${n%60?`${n%60}min`:""}`;
type FoodSuggestionState={status:"checking"|"available"|"empty"|"loading"|"ready"|"failed";candidates:FoodCandidate[]};
const foodSuggestionStates=new Map<string,FoodSuggestionState>();
const foodSuggestionKey=(day:number,index:number)=>`${day}:${index}`;
function resetGuideSummaries(){placeGuideSummaries.clear();guideSummaryState="idle";guideSummaryStale=true;}
async function buildGuideSummaries(){const inputs=places.filter(p=>p.poiStatus==="resolved"&&(p.evidence?.length??0)>0).map(p=>({placeId:p.id,name:p.name??p.rawName,evidence:p.evidence??[]}));if(!inputs.length){guideSummaryState="ready";guideSummaryStale=false;render();return;}guideSummaryState="loading";render();try{const summaries=await summarizePlaceGuides(inputs);placeGuideSummaries=new Map(summaries.map(summary=>[summary.placeId,summary]));guideSummaryState="ready";guideSummaryStale=false;}catch{guideSummaryState="failed";guideSummaryStale=false;}render();}
const guideList=(items:string[],limit:number,expanded:boolean)=>`<ul>${items.slice(0,expanded?items.length:limit).map(item=>`<li>${esc(item)}</li>`).join("")}</ul>`;
function guideDetails(place:Place){const summary=placeGuideSummaries.get(place.id),expanded=expandedGuidePlaceIds.has(place.id),fallback=place.tips?.length?`<section class="guide-section guide-fallback"><h4><i>i</i>攻略里提到</h4>${guideList(place.tips,2,expanded)}</section>`:"";if(guideSummaryState==="loading"&&guideSummaryStale)return `<div class="guide-loading">正在整理你的攻略…</div>`;if(!summary){return guideSummaryState==="failed"?`${fallback}<p class="guide-error">攻略整理暂时失败</p>`:fallback;}const parts=[summary.oneLineSummary?`<section class="guide-section guide-one-line"><h4><i>✦</i>一句话</h4><p>${esc(summary.oneLineSummary)}</p></section>`:"",summary.repeatedPoints.length?`<section class="guide-section"><h4><i>↻</i>反复提到</h4>${guideList(summary.repeatedPoints,3,expanded)}</section>`:"",summary.practicalTips.length?`<section class="guide-section"><h4><i>i</i>实用提醒</h4>${guideList(summary.practicalTips,3,expanded)}</section>`:"",summary.conflicts.length?`<section class="guide-section"><h4><i>↔</i>说法不一</h4>${summary.conflicts.slice(0,expanded?summary.conflicts.length:2).map(conflict=>`<div class="guide-conflict"><b>${esc(conflict.topic)}</b>${guideList(conflict.viewpoints,99,true)}</div>`).join("")}</section>`:""].filter(Boolean);const total=summary.repeatedPoints.length+summary.practicalTips.length+summary.conflicts.length;return `${parts.join("")||fallback}${total>3?`<button class="guide-more" data-guide-more="${place.id}">${expanded?"收起":"查看更多"}</button>`:""}`;}
const resolved=(p:Place):ResolvedPlace|undefined=>p.poiStatus==="resolved"&&p.poiId&&p.name&&p.address&&p.longitude!==undefined&&p.latitude!==undefined?{status:"resolved",placeId:p.id,poiId:p.poiId,name:p.name,address:p.address,longitude:p.longitude,latitude:p.latitude,category:p.category,tips:p.tips,type:p.type,recommendationScore:p.recommendationScore,mustVisit:p.mustVisit}:undefined;
function selectedHotelResolved():ResolvedPlace|undefined{return selectedHotel?resolved(selectedHotel):undefined;}
function refreshMap(focusDay?:number){if(!mapReady)return;mapView.showPlaces(places.map(resolved).filter((x):x is ResolvedPlace=>!!x),routePlanningResult?.days??[],{selectedDay,selectedPlaceId,focusDay,onPlaceClick:selectFromMap,stayAreas:stayState.status==="ready"?stayState.areas:[],selectedStayAreaId,selectedHotel:selectedHotelResolved()});}
function markStayStale(){if(stayState.status==="ready")stayState={...stayState,stale:true};}
function stale(){if(routePlanningResult)routeStale=true;markStayStale();planningResult=undefined;refreshMap();render();}
function clearFoodSuggestions(days?:number[]){if(!days){foodSuggestionStates.clear();return;}for(const key of foodSuggestionStates.keys())if(days.includes(Number(key.split(":")[0])))foodSuggestionStates.delete(key);}
function allScheduledIds(){return new Set(routePlanningResult?.days.flatMap(day=>day.orderedPlaceIds)??[]);}
function syncUnassignedPlaces(){const scheduled=allScheduledIds(),existing=new Set(places.map(place=>place.id));unassignedPlaceIds=[...new Set(unassignedPlaceIds)].filter(id=>existing.has(id)&&!scheduled.has(id));}
function moveToUnassigned(placeId:string){if(!routePlanningResult)return;markStayStale();const affected=routePlanningResult.days.filter(day=>day.orderedPlaceIds.includes(placeId)).map(day=>day.day);routePlanningResult.days.forEach(day=>{day.orderedPlaceIds=day.orderedPlaceIds.filter(id=>id!==placeId);day.placeIds=[...day.orderedPlaceIds];day.orderSource="manual";});if(!unassignedPlaceIds.includes(placeId))unassignedPlaceIds.push(placeId);const place=places.find(p=>p.id===placeId);if(place)place.manualDayOverride=null;void rebuildAffectedDays(affected);}
function moveToDay(placeId:string,dayNumber:number,index?:number){if(!routePlanningResult)return;markStayStale();const affected=new Set<number>();routePlanningResult.days.forEach(day=>{if(day.orderedPlaceIds.includes(placeId)){day.orderedPlaceIds=day.orderedPlaceIds.filter(id=>id!==placeId);day.placeIds=[...day.orderedPlaceIds];day.orderSource="manual";affected.add(day.day);}});let day=routePlanningResult.days.find(item=>item.day===dayNumber);if(!day){day={day:dayNumber,placeIds:[],orderedPlaceIds:[],segments:[],totalActivityMinutes:0,totalTransitMinutes:0,warnings:[],orderSource:"manual"};routePlanningResult.days.push(day);routePlanningResult.days.sort((a,b)=>a.day-b.day);}const at=Math.max(0,Math.min(index??day.orderedPlaceIds.length,day.orderedPlaceIds.length));day.orderedPlaceIds.splice(at,0,placeId);day.placeIds=[...day.orderedPlaceIds];day.orderSource="manual";affected.add(day.day);unassignedPlaceIds=unassignedPlaceIds.filter(id=>id!==placeId);const place=places.find(p=>p.id===placeId);if(place)place.manualDayOverride=dayNumber;void rebuildAffectedDays([...affected]);}
async function rebuildAffectedDays(days:number[]){if(!routePlanningResult)return;clearFoodSuggestions(days);const affected=new Set(days);routePlanningResult.days.forEach(day=>{if(affected.has(day.day))day.isUpdating=true;});render();refreshMap();for(const dayNumber of affected){const index=routePlanningResult.days.findIndex(day=>day.day===dayNumber);const current=routePlanningResult.days[index];if(!current)continue;try{routePlanningResult.days[index]=await rebuildManualDay(dayNumber,current.orderedPlaceIds,places,planningCity,resolveAmapRoute);}catch{routePlanningResult.days[index]={...current,isUpdating:false,warnings:[...current.warnings,"路线暂时无法获取。"]};}}routePlanningResult.days.forEach(day=>day.isUpdating=false);routePlanningResult.warnings=routePlanningResult.days.flatMap(day=>day.warnings);render();refreshMap();}
async function searchManual(keyword:string){if(!keyword.trim())return;manualSearchLoading=true;render();try{manualSearchResults=await searchPoiCandidates({city:planningCity||city.value,keyword});}catch{manualSearchResults=[];msg("高德地点搜索失败，请稍后重试。",true);}finally{manualSearchLoading=false;render();}}
function addManualPlace(candidate:PoiCandidate){if(places.some(place=>place.poiId===candidate.poiId)){msg("这个地点已经在你的行程里了。",true);return;}const type=placeTypeFromVisual[getPlaceVisual({category:candidate.poiType})];const id=`manual-${candidate.poiId}`;places.push({id,rawName:candidate.name,name:candidate.name,poiStatus:"resolved",poiId:candidate.poiId,address:candidate.address,longitude:candidate.longitude,latitude:candidate.latitude,category:candidate.poiType,source:"manual",tips:[],evidence:[],type,estimatedDurationMinutes:60,durationSource:"default",recommendationScore:3,recommendationReason:"手动添加地点",mustVisit:false,manualDayOverride:null});unassignedPlaceIds.push(id);manualSearchOpen=false;manualSearchResults=[];render();refreshMap();msg(`${candidate.name} 已加入暂未安排。`);}
function prefs():TripPreferences{const days=($<HTMLSelectElement>("#trip-days")?.value??"auto"),pace=($<HTMLButtonElement>("[data-pace].active")?.dataset.pace??"flexible") as Pace;return{tripDays:days==="auto"?null:Number(days),tripNights:days==="auto"?null:Math.max(0,Number(days)-1),durationMode:days==="auto"?"auto":"user_selected",pace};}
function renderSettings(){const p=prefs(), done=!!routePlanningResult&&!routeStale;settings.innerHTML=done&&!settingsExpanded?`<div class="settings-title">行程设置 <button id="edit-settings">修改</button></div><p class="settings-summary">📍 ${esc(city.value||"未设置")} · 🗓 ${p.tripDays?`${p.tripDays}天${p.tripNights?`${p.tripNights}晚`:""}`:"自动建议"} · ☕ ${({vacation:"度假",relaxed:"轻松",flexible:"随便",compact:"紧凑",intense:"特种兵"})[p.pace]}</p>`:`<div class="settings-title">行程设置</div><div class="settings-grid"><label>目的地<input id="settings-city" value="${esc(city.value)}" /></label><label>行程时长<select id="trip-days"><option value="auto">随便</option>${[1,2,3,4,5].map(d=>`<option value="${d}" ${p.tripDays===d?"selected":""}>${d===1?"1天":`${d}天${d-1}晚`}</option>`).join("")}</select></label></div><small>随便：根据地点数量和停留时长自动建议</small><p class="setting-label">旅行节奏</p><div class="pace-picker">${([['vacation','度假'],['relaxed','轻松'],['flexible','随便'],['compact','紧凑'],['intense','特种兵']] as const).map(([k,l])=>`<button data-pace="${k}" class="${p.pace===k?"active":""}">${l}</button>`).join("")}</div><p class="pace-help">${({vacation:"少排一点，给休息和临时探索留空间。",relaxed:"行程偏松，不追求打卡数量。",flexible:"在地点数量和松弛感之间保持平衡。",compact:"尽量多排地点，但避免明显折返。",intense:"优先多打卡，接受更紧凑的安排。"})[p.pace]}</p><button id="generate-plan" class="generate-button">${routePlanningResult?"重新生成":"生成行程"}</button>`;$<HTMLButtonElement>("#edit-settings")?.addEventListener("click",()=>{settingsExpanded=true;render()});$<HTMLInputElement>("#settings-city")?.addEventListener("change",e=>{city.value=(e.target as HTMLInputElement).value;planningCity=city.value.trim();stale()});$<HTMLSelectElement>("#trip-days")?.addEventListener("change",stale);document.querySelectorAll<HTMLButtonElement>("[data-pace]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-pace]").forEach(x=>x.classList.remove("active"));b.classList.add("active");stale()}));$<HTMLButtonElement>("#generate-plan")?.addEventListener("click",()=>void generate());}
function renderPlaces(){const labels:Record<Place["poiStatus"],string>={resolved:"已定位",ambiguous:"需要确认",not_found:"未找到",failed:"搜索失败",unresolved:"待确认"};const visible=places.filter(p=>p.recommendationScore>=scoreFilter);list.innerHTML=visible.map(p=>`<li class="place-card ${selectedPlaceId===p.id?"selected":""}" data-place-card="${p.id}"><div class="place-card-header"><div><span class="place-name">${typeIcon(p.type,p.category)} ${esc(p.rawName)}</span><span class="type-badge">${typeLabel(p.type)}</span></div><span class="state state-${p.poiStatus}">${labels[p.poiStatus]}</span><button class="delete" data-delete="${p.id}">删除</button></div><div class="score-row"><strong>${"★".repeat(p.recommendationScore)}${"☆".repeat(5-p.recommendationScore)}</strong></div><p class="reason">${esc(p.recommendationReason??"攻略未表达明显倾向")}</p><div class="place-meta"><label>预计停留 <select data-duration="${p.id}">${[[30,"30m"],[60,"1h"],[90,"1.5h"],[120,"2h"],[180,"3h"],[240,"4h"],[480,"全天"]].map(([v,l])=>`<option value="${v}" ${p.estimatedDurationMinutes===v?"selected":""}>${l}</option>`).join("")}</select></label><button data-must="${p.id}" class="must-visit ${p.mustVisit?"active":""}">${p.mustVisit?"♥ 必去":"♡ 设为必去"}</button></div>${p.tips?.length?`<p class="tips">攻略提示：${p.tips.map(esc).join("；")}</p>`:""}${p.poiStatus==="ambiguous"?`<div class="candidates"><p>你想去的是：</p>${(p.poiCandidates??[]).map((c,i)=>`<button class="candidate" data-candidate="${p.id}:${i}"><strong>${esc(c.name)}</strong><span>${esc(c.address)}</span></button>`).join("")}</div>`:""}</li>`).join("");list.querySelectorAll<HTMLElement>("[data-place-card]").forEach(card=>card.onclick=e=>{if((e.target as HTMLElement).closest("button,select"))return;selectStop(card.dataset.placeCard!)});list.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach(b=>b.onclick=()=>{places=places.filter(p=>p.id!==b.dataset.delete);stale()});list.querySelectorAll<HTMLSelectElement>("[data-duration]").forEach(s=>s.onchange=()=>{const p=places.find(x=>x.id===s.dataset.duration);if(p){p.estimatedDurationMinutes=Number(s.value);p.durationEdited=true;stale()}});list.querySelectorAll<HTMLButtonElement>("[data-must]").forEach(b=>b.onclick=()=>{const p=places.find(x=>x.id===b.dataset.must);if(p){p.mustVisit=!p.mustVisit;stale()}});list.querySelectorAll<HTMLButtonElement>("[data-candidate]").forEach(b=>b.onclick=()=>{const[id,i]=b.dataset.candidate!.split(":");const p=places.find(x=>x.id===id),c=p?.poiCandidates?.[Number(i)];if(p&&c){Object.assign(p,c,{poiStatus:"resolved"});places=dedupeResolvedPlaces(places).places;resetGuideSummaries();stale()}});}
function renderItinerary(){
  if(!routePlanningResult){itinerary.innerHTML=`<div class="empty-itinerary">生成行程后，在这里查看每天的路线与通勤。</div>`;return;}
  syncUnassignedPlaces();
  const pool=unassignedPlaceIds.map(id=>places.find(place=>place.id===id)).filter((place):place is Place=>Boolean(place));
  itinerary.innerHTML=`${routeStale?`<div class="stale-notice">● 地点或行程条件已变化<br><button id="stale-generate">重新生成</button></div>`:""}<section class="unassigned" data-drop-day="unassigned"><div class="unassigned-head"><strong>暂未安排 · ${pool.length}</strong><button id="open-manual-search">+ 添加地点</button></div>${pool.length?`<div class="unassigned-chips">${pool.map(place=>`<button draggable="true" class="unassigned-chip" data-drag-place="${place.id}">${typeIcon(place.type,place.category)} ${esc(place.rawName)}</button>`).join("")}</div>`:`<p>暂无地点，可搜索添加，或把某天地点拖到这里。</p>`}${manualSearchOpen?`<div class="manual-search"><input id="manual-query" placeholder="搜索真实地点" /><button id="manual-search-button">搜索</button>${manualSearchLoading?"<p>正在搜索高德地点…</p>":manualSearchResults.map(candidate=>`<div class="manual-result"><strong>${typeIcon(undefined,candidate.poiType)} ${esc(candidate.name)}</strong><span>${esc([candidate.poiType,candidate.address].filter(Boolean).join(" · "))}</span><button data-add-poi="${candidate.poiId}">加入</button></div>`).join("")}</div>`:""}</section>${routePlanningResult.days.map(day=>dayCard(day)).join("")}${stayModuleMarkup()}`;
  $<HTMLButtonElement>("#stale-generate")?.addEventListener("click",()=>void generate());
  $<HTMLButtonElement>("#open-manual-search")?.addEventListener("click",()=>{manualSearchOpen=!manualSearchOpen;render();});
  $<HTMLButtonElement>("#manual-search-button")?.addEventListener("click",()=>void searchManual($<HTMLInputElement>("#manual-query").value));
  document.querySelectorAll<HTMLButtonElement>("[data-add-poi]").forEach(button=>button.onclick=()=>{const candidate=manualSearchResults.find(item=>item.poiId===button.dataset.addPoi);if(candidate)addManualPlace(candidate);});
  document.querySelectorAll<HTMLButtonElement>("[data-day]").forEach(b=>b.onclick=()=>{const d=Number(b.dataset.day);selectedDay=selectedDay===d?undefined:d;if(selectedDay)expandedDays.add(d);render();refreshMap(selectedDay)});
  document.querySelectorAll<HTMLButtonElement>("[data-stop]").forEach(b=>b.onclick=()=>selectStop(b.dataset.stop!));
  document.querySelectorAll<HTMLButtonElement>("[data-guide-more]").forEach(b=>b.onclick=()=>{const id=b.dataset.guideMore!;expandedGuidePlaceIds.has(id)?expandedGuidePlaceIds.delete(id):expandedGuidePlaceIds.add(id);render();});
  document.querySelectorAll<HTMLButtonElement>("[data-open-food]").forEach(button=>button.onclick=()=>{const [day,index]=button.dataset.openFood!.split(":").map(Number);void openAlongRouteFood(day,index);});
  document.querySelectorAll<HTMLButtonElement>("[data-stay-recommend]").forEach(button=>button.onclick=()=>void generateStayRecommendations());
  document.querySelectorAll<HTMLButtonElement>("[data-focus-stay]").forEach(button=>button.onclick=()=>{const area=stayState.areas.find(item=>item.anchorPoiId===button.dataset.focusStay);if(area){selectedStayAreaId=area.anchorPoiId;mapView.focusStayArea(area);render();refreshMap();}});
  document.querySelectorAll<HTMLButtonElement>("[data-load-hotels]").forEach(button=>button.onclick=()=>void loadStayHotels(button.dataset.loadHotels!));
  document.querySelectorAll<HTMLButtonElement>("[data-select-hotel]").forEach(button=>button.onclick=()=>{const [areaId,index]=button.dataset.selectHotel!.split(":");selectStayHotel(areaId,Number(index));});
  document.querySelectorAll<HTMLButtonElement>("[data-add-food-here]").forEach(button=>button.onclick=()=>{const [key,index]=button.dataset.addFoodHere!.split("#");const candidate=foodSuggestionStates.get(key)?.candidates[Number(index)], [day,segmentIndex]=key.split(":").map(Number);if(candidate)addFoodCandidate(candidate,day,segmentIndex+1);});
  document.querySelectorAll<HTMLButtonElement>("[data-add-food-unassigned]").forEach(button=>button.onclick=()=>{const [key,index]=button.dataset.addFoodUnassigned!.split("#");const candidate=foodSuggestionStates.get(key)?.candidates[Number(index)];if(candidate)addFoodCandidate(candidate);});
  document.querySelectorAll<HTMLElement>("[data-food-precheck]").forEach(node=>{const [day,index]=node.dataset.foodPrecheck!.split(":").map(Number);void ensureAlongRouteFood(day,index);});
  document.querySelectorAll<HTMLElement>("[data-drag-place]").forEach(item=>{item.ondragstart=event=>event.dataTransfer?.setData("text/place-id",item.dataset.dragPlace!)});
  document.querySelectorAll<HTMLElement>("[data-drop-day]").forEach(target=>{target.ondragover=event=>event.preventDefault();target.ondrop=event=>{event.preventDefault();const id=event.dataTransfer?.getData("text/place-id");if(!id)return;target.dataset.dropDay==="unassigned"?moveToUnassigned(id):moveToDay(id,Number(target.dataset.dropDay),Number(target.dataset.dropIndex));};});
}
const expandedDays=new Set<number>(),expandedGuidePlaceIds=new Set<string>();
function foodSuggestionMarkup(day:number,index:number,segment:DayRoute["segments"][number]|undefined){
  if(!segment||segment.status!=="resolved"||segment.durationMinutes===null||segment.durationMinutes<15||segment.path.length<3)return "";
  const endpointPlaces=[segment.fromPlaceId,segment.toPlaceId].map(id=>places.find(place=>place.id===id)).filter((place):place is Place=>Boolean(place));
  if(endpointPlaces.some(place=>getPlaceVisual({type:place.type,category:place.category})==="eat"))return "";
  const key=foodSuggestionKey(day,index),state=foodSuggestionStates.get(key);
  if(!state)return `<div class="food-suggestion" data-food-precheck="${key}">正在看看附近有没有适合顺路吃的…</div>`;
  if(state.status==="checking")return `<div class="food-suggestion">正在看看附近有没有适合顺路吃的…</div>`;
  if(state.status==="failed")return `<div class="food-suggestion muted">附近餐厅暂未获取</div>`;
  if(state.status==="empty")return `<div class="food-suggestion muted">这段路附近暂时没有适合顺路加入的餐厅</div>`;
  if(state.status==="available")return `<div class="food-suggestion"><button data-open-food="${key}">◒ 路上找吃的</button></div>`;
  if(state.status==="loading")return `<div class="food-suggestion">正在计算顺路程度…</div>`;
  return `<div class="food-suggestion food-options"><p>顺路吃点什么</p>${state.candidates.map((candidate,index)=>`<div class="food-option"><div><strong>◒ ${esc(candidate.name)}</strong><span>${esc([candidate.category,candidate.rating?`${candidate.rating}分`:"",candidate.cost].filter(Boolean).join(" · "))}</span>${candidate.detourMinutes!==undefined?`<em>额外约 ${mins(candidate.detourMinutes)}</em>`:""}</div><div><button data-add-food-here="${key}#${index}">加到这里</button><button class="quiet" data-add-food-unassigned="${key}#${index}">暂不安排</button></div></div>`).join("")}</div>`;
}
function stayModuleMarkup(){
  if(stayState.status==="loading")return `<section class="stay-module"><p class="stay-kicker">🛏 还没决定住哪？</p><strong>正在根据当前多日路线确认住宿区域…</strong><small>先找真实交通锚点，再验证每天的首尾通勤。</small></section>`;
  if(stayState.status==="error")return `<section class="stay-module"><p class="stay-kicker">🛏 还没决定住哪？</p><strong>住宿区域暂未获取</strong><button data-stay-recommend>重新推荐</button></section>`;
  if(stayState.status!=="ready")return `<section class="stay-module"><p class="stay-kicker">🛏 还没决定住哪？</p><strong>根据你这几天的路线，找几个整体比较方便的住宿区域。</strong><button data-stay-recommend>推荐住宿</button></section>`;
  return `<section class="stay-module"><div class="stay-module-head"><div><p class="stay-kicker">🛏 住宿区域建议</p>${stayState.stale?`<small class="stay-stale">行程已调整，住宿建议可能需要更新。</small>`:""}</div><button data-stay-recommend>重新推荐</button></div>${selectedHotel?`<div class="selected-hotel">🛏 已选住宿：<strong>${esc(selectedHotel.name??selectedHotel.rawName)}</strong></div>`:""}${stayState.areas.length?stayState.areas.map(stayAreaCard).join(""):`<p class="stay-empty">暂时没有足够的真实交通数据生成区域建议。</p>`}</section>`;
}
function stayAreaCard(area:StayAreaCandidate){const selected=area.anchorPoiId===selectedStayAreaId,hotelLines=area.hotels?.map((hotel,index)=>`<div class="hotel-option"><div><strong>▣ ${esc(hotel.name)}</strong><span>${[hotel.rating?`${hotel.rating} 分`:"",`距地铁站 ${hotel.distanceToAnchorMeters}m`].filter(Boolean).join(" · ")}</span>${hotel.cost?`<em>参考消费：${esc(hotel.cost)}</em>`:""}</div><button data-select-hotel="${area.anchorPoiId}:${index}">选为住宿</button></div>`).join("")??"";return `<article class="stay-area-card ${selected?"selected":""}" data-stay-area="${area.anchorPoiId}"><button class="stay-area-focus" data-focus-stay="${area.anchorPoiId}"><strong>🛏 ${esc(area.anchorName)}</strong><span>${esc(area.explanation)}</span></button><div class="stay-days">${area.perDayCommuteMinutes.map(item=>`<span>Day ${item.day} 首尾约 ${item.minutes}min</span>`).join("")}</div><p>多日首尾通勤合计约 ${area.totalCommuteMinutes}min</p>${area.hotelStatus==="loading"?`<div class="stay-hotels-loading">正在搜索附近真实酒店…</div>`:area.hotelStatus==="ready"?`<div class="stay-hotels">${hotelLines||"<p>附近暂未找到合适酒店。</p>"}</div>`:`<button data-load-hotels="${area.anchorPoiId}">查看酒店</button>`}</article>`;}
async function generateStayRecommendations(){if(!routePlanningResult)return;stayState={...stayState,status:"loading",stale:false};render();try{const areas=await recommendStayAreas(routePlanningResult.days,places,planningCity);stayState={status:"ready",areas,stale:false,routeVersion:routePlanningResult.days.map(day=>`${day.day}:${day.orderedPlaceIds.join(",")}`).join("|")};selectedStayAreaId=areas[0]?.anchorPoiId;msg(areas.length?`已生成 ${areas.length} 个真实交通锚点周边的住宿建议。`:"暂未找到足够的真实住宿区域候选。",!areas.length);}catch{stayState={...stayState,status:"error",stale:true};msg("住宿区域生成失败，请稍后重试。",true);}render();refreshMap();}
async function loadStayHotels(anchorPoiId:string){const area=stayState.areas.find(item=>item.anchorPoiId===anchorPoiId);if(!area||area.hotelStatus==="loading"||area.hotelStatus==="ready")return;area.hotelStatus="loading";render();try{area.hotels=await findHotelsNearStayArea(area,planningCity);area.hotelStatus="ready";}catch{area.hotelStatus="error";msg("附近酒店搜索失败，请稍后重试。",true);}render();}
function selectStayHotel(areaId:string,index:number){const area=stayState.areas.find(item=>item.anchorPoiId===areaId),hotel=area?.hotels?.[index];if(!area||!hotel)return;selectedHotel={id:`selected-hotel-${hotel.poiId}`,rawName:hotel.name,name:hotel.name,poiStatus:"resolved",poiId:hotel.poiId,address:hotel.address,longitude:hotel.longitude,latitude:hotel.latitude,category:hotel.category??"酒店",type:"hotel",source:"stay_recommendation",tips:[],evidence:[],estimatedDurationMinutes:null,durationSource:"unknown",recommendationScore:3,recommendationReason:`住宿推荐：${area.anchorName}`,mustVisit:false};selectedStayAreaId=areaId;render();refreshMap();msg(`${hotel.name} 已设为本次旅行的住宿，不会加入日程或暂未安排。`);}
function dayCard(d:DayRoute){const open=expandedDays.has(d.day),names=d.orderedPlaceIds.map(id=>places.find(p=>p.id===id)?.rawName??"地点"),summary=names.length>4?`${names.slice(0,3).join(" → ")} → +${names.length-3}`:names.join(" → "),over=d.totalActivityMinutes>480;return `<article class="day-card ${selectedDay===d.day?"selected-day":""}" data-drop-day="${d.day}" data-drop-index="${d.orderedPlaceIds.length}"><button class="day-head" data-day="${d.day}"><span class="day-dot day-${d.day}"></span><span>Day ${d.day}</span><small>${names.length} 个地点${d.orderSource==="manual"?" · 已手动调整":""}</small><b>${open?"收起":"查看详情"}</b></button><p class="day-metrics">${d.isUpdating?"正在更新路线…":`游玩 ${mins(d.totalActivityMinutes)} · 通勤 ${d.totalTransitMinutes===null?"部分未获取":mins(d.totalTransitMinutes)}`}</p>${over?"<p class=\"day-warning\">这一天可能偏赶</p>":""}${!open?(names.length?`<p class="day-order">${esc(summary)}</p>`:"<p class=\"day-order\">这一天暂时没有安排</p>"):`<div class="timeline">${d.orderedPlaceIds.map((id,i)=>{const p=places.find(x=>x.id===id)!,seg=d.segments[i-1],active=selectedPlaceId===id;return `${i?`<div class="timeline-segment ${seg?.status==="failed"?"failed":""}">↓ ${seg?.status==="failed"?"路线暂未获取":`${seg?.transportMode==="walking"?"步行":"公交 / 地铁"} ${mins(seg?.durationMinutes??null)}`}</div>${foodSuggestionMarkup(d.day,i-1,seg)}`:""}<div class="timeline-item" data-drop-day="${d.day}" data-drop-index="${i}" draggable="true" data-drag-place="${id}"><button class="timeline-stop ${active?"selected":""}" data-stop="${id}"><strong>⠿ ${typeIcon(p.type,p.category)} ${esc(p.rawName)}</strong><span>${typeLabel(p.type)} · ${mins(p.estimatedDurationMinutes??60)} · ${"★".repeat(p.recommendationScore)}</span></button>${active?`<div class="guide-details">${guideDetails(p)}</div>`:""}</div>`}).join("")}</div>`}${d.warnings.length?`<p class="day-warning">部分通勤路线暂未获取</p>`:""}</article>`}
function findRouteSegment(dayNumber:number,index:number){const day=routePlanningResult?.days.find(item=>item.day===dayNumber),segment=day?.segments[index];if(!day||!segment)return;const from=places.find(place=>place.id===segment.fromPlaceId),to=places.find(place=>place.id===segment.toPlaceId);return from&&to?{day,segment,from,to}:undefined;}
async function ensureAlongRouteFood(dayNumber:number,index:number){const found=findRouteSegment(dayNumber,index),key=foodSuggestionKey(dayNumber,index);if(!found||foodSuggestionStates.has(key))return;foodSuggestionStates.set(key,{status:"checking",candidates:[]});render();try{const candidates=await precheckAlongRouteFood(found.segment,planningCity);foodSuggestionStates.set(key,{status:candidates.length?"available":"empty",candidates});}catch{foodSuggestionStates.set(key,{status:"failed",candidates:[]});}render();}
async function openAlongRouteFood(dayNumber:number,index:number){const found=findRouteSegment(dayNumber,index),key=foodSuggestionKey(dayNumber,index);if(!found)return;foodSuggestionStates.set(key,{status:"loading",candidates:[]});render();try{const candidates=await rankAlongRouteFood(found.segment,found.from,found.to,planningCity);foodSuggestionStates.set(key,{status:candidates.length?"ready":"empty",candidates});}catch{foodSuggestionStates.set(key,{status:"failed",candidates:[]});}render();}
function addFoodCandidate(candidate:FoodCandidate,dayNumber?:number,insertIndex?:number){if(places.some(place=>place.poiId===candidate.poiId)){msg("这个地点已经在你的行程里了。",true);return;}const id=`food-${candidate.poiId}`;places.push({id,rawName:candidate.name,name:candidate.name,poiStatus:"resolved",poiId:candidate.poiId,address:candidate.address,longitude:candidate.longitude,latitude:candidate.latitude,category:candidate.category,source:"manual",tips:[],evidence:[],type:placeTypeFromVisual.eat,estimatedDurationMinutes:60,durationSource:"default",recommendationScore:3,recommendationReason:"路线中途手动添加餐饮",mustVisit:false,manualDayOverride:null});if(dayNumber!==undefined)moveToDay(id,dayNumber,insertIndex);else{unassignedPlaceIds.push(id);render();refreshMap();}msg(`${candidate.name} 已加入${dayNumber!==undefined?` Day ${dayNumber}`:"暂未安排"}。`);}
function renderPlaceSearch(){const slot=$<HTMLElement>("#place-manual-search");if(activeTab!=="places"){slot.innerHTML="";return;}slot.innerHTML=manualSearchOpen?`<div class="manual-search place-search"><input id="place-search-query" placeholder="搜索真实地点" /><button id="place-search-button">搜索</button>${manualSearchLoading?"<p>正在搜索高德地点…</p>":manualSearchResults.map(candidate=>`<div class="manual-result"><strong>${typeIcon(undefined,candidate.poiType)} ${esc(candidate.name)}</strong><span>${esc([candidate.poiType,candidate.address].filter(Boolean).join(" · "))}</span><button data-add-poi="${candidate.poiId}">加入</button></div>`).join("")}</div>`:"";const addButton=$<HTMLButtonElement>("#add-place-from-list");addButton.onclick=()=>{manualSearchOpen=!manualSearchOpen;render();};$<HTMLButtonElement>("#place-search-button")?.addEventListener("click",()=>void searchManual($<HTMLInputElement>("#place-search-query").value));slot.querySelectorAll<HTMLButtonElement>("[data-add-poi]").forEach(button=>button.onclick=()=>{const candidate=manualSearchResults.find(item=>item.poiId===button.dataset.addPoi);if(candidate)addManualPlace(candidate);});}
function removeFromTrip(placeId:string){const affected=routePlanningResult?.days.filter(day=>day.orderedPlaceIds.includes(placeId)).map(day=>day.day)??[];places=places.filter(place=>place.id!==placeId);unassignedPlaceIds=unassignedPlaceIds.filter(id=>id!==placeId);routePlanningResult?.days.forEach(day=>{day.orderedPlaceIds=day.orderedPlaceIds.filter(id=>id!==placeId);day.placeIds=[...day.orderedPlaceIds];});if(affected.length)void rebuildAffectedDays(affected);else{render();refreshMap();}}
function stopNestedDropBubbling(){document.querySelectorAll<HTMLElement>(".timeline-item[data-drop-day]").forEach(item=>item.addEventListener("drop",event=>event.stopPropagation()));}
function render(){workspace.hidden=!places.length;$<HTMLElement>("#place-count").textContent=String(places.length);$<HTMLElement>("#day-count").textContent=routePlanningResult?`${routePlanningResult.days.length}天`:"—";renderSettings();renderPlaces();renderPlaceSearch();renderItinerary();stopNestedDropBubbling();$<HTMLElement>("#places-view").hidden=activeTab!=="places";itinerary.hidden=activeTab!=="itinerary";$<HTMLElement>("#tab-places").classList.toggle("active",activeTab==="places");$<HTMLElement>("#tab-itinerary").classList.toggle("active",activeTab==="itinerary");}
function selectStop(id:string){selectedPlaceId=id;const p=places.find(x=>x.id===id),r=p&&resolved(p);if(r)mapView.focusPlace(r);render();refreshMap();}
function selectFromMap(id:string){selectedPlaceId=id;const d=routePlanningResult?.days.find(x=>x.orderedPlaceIds.includes(id));if(d){activeTab="itinerary";selectedDay=d.day;expandedDays.add(d.day);}render();setTimeout(()=>document.querySelector(`[data-stop="${CSS.escape(id)}"]`)?.scrollIntoView({block:"center",behavior:"smooth"}),0);}
async function ground(cityName:string){msg("正在确认地点……");const rs:{p:Place;r:Awaited<ReturnType<typeof resolvePlace>>}[]=[];for(const p of places){rs.push({p,r:await resolvePlace({city:cityName,name:p.rawName})});}places=rs.map(({p,r})=>r.status==="resolved"?{...p,...r,poiStatus:"resolved"}:r.status==="ambiguous"?{...p,poiStatus:"ambiguous",poiCandidates:r.candidates}:{...p,poiStatus:r.status});places=dedupeResolvedPlaces(places).places;render();refreshMap();msg(`${places.filter(p=>p.poiStatus==="resolved").length} 个地点已确认；其余地点可继续确认。`)}
async function extract(){const text=notes.value.trim();if(!text&&!images.length){msg("请粘贴攻略文本或上传至少一张截图。",true);return;}const b=$<HTMLButtonElement>("#extract-button");b.disabled=true;try{msg("正在从攻略里找你种草的地方……");const out=await extractPlaces(text,images),c=city.value.trim()||out.city;if(!c)throw new Error("未能判断城市，请先填写城市后再试。");planningCity=c;city.value=c;places=out.places.map((p,i)=>({id:`${p.name}-${i}`,rawName:p.name,poiStatus:"unresolved",mustVisit:false,...p}));resetGuideSummaries();clearFoodSuggestions();stayState={status:"idle",areas:[],stale:false};selectedStayAreaId=undefined;selectedHotel=undefined;routePlanningResult=undefined;planningResult=undefined;routeStale=false;inputArea.hidden=true;inputSummary.hidden=false;inputSummaryText.textContent=`已导入 ${images.length?`${images.length} 张图片`:"一段攻略"} · 识别中`;await ground(c);inputSummaryText.textContent=`已导入 ${images.length?`${images.length} 张图片`:"一段攻略"} · 识别 ${places.length} 个地点`;}catch(e){msg(e instanceof Error?e.message:"攻略解析失败。",true)}finally{b.disabled=false}}
async function generate(){if(!planningCity){msg("请先确认目的地。",true);return;}const b=$<HTMLButtonElement>("#generate-plan");if(b)b.disabled=true;try{planningResult=groupPlaces(places,prefs());clearFoodSuggestions();markStayStale();msg("正在通过高德确认日内路线……");routePlanningResult=await planRoutes(planningResult.groups,places,planningCity,resolveAmapRoute);routeStale=false;settingsExpanded=false;activeTab="itinerary";selectedDay=undefined;render();refreshMap();msg(routePlanningResult.warnings.length?"行程已生成，部分路线暂未获取。":"已生成真实高德行程。");if(guideSummaryStale)void buildGuideSummaries();}catch(e){msg(e instanceof Error?e.message:"行程生成失败。",true)}finally{if(b)b.disabled=false}}
$<HTMLButtonElement>("#extract-button").onclick=()=>void extract();$<HTMLButtonElement>("#edit-input").onclick=()=>{inputArea.hidden=!inputArea.hidden;$<HTMLButtonElement>("#edit-input").textContent=inputArea.hidden?"展开原始输入":"收起原始输入"};$<HTMLButtonElement>("#tab-places").onclick=()=>{activeTab="places";render()};$<HTMLButtonElement>("#tab-itinerary").onclick=()=>{activeTab="itinerary";render()};document.querySelectorAll<HTMLButtonElement>("[data-filter]").forEach(b=>b.onclick=()=>{scoreFilter=Number(b.dataset.filter);renderPlaces()});$<HTMLButtonElement>("#remove-low").onclick=()=>{places=places.filter(p=>p.recommendationScore>=3||p.mustVisit);stale()};
imageInput.onchange=async()=>{const fs=[...(imageInput.files??[])],add=fs.filter(f=>!imageKeys.has(`${f.name}-${f.size}-${f.lastModified}`));if(images.length+add.length>6||add.some(f=>f.size>5*1024*1024)){msg("最多上传 6 张图片，单张不超过 5MB。",true);return;}const data=await Promise.all(add.map(f=>new Promise<ImageInput>((ok,no)=>{const r=new FileReader();r.onload=()=>ok({mimeType:f.type,data:String(r.result).split(",")[1]});r.onerror=no;r.readAsDataURL(f)})));add.forEach(f=>imageKeys.add(`${f.name}-${f.size}-${f.lastModified}`));images.push(...data);imageInput.value="";previews.textContent=`已选择 ${images.length} 张攻略截图，可继续选择追加。`};
void mapView.mount($<HTMLElement>("#map")).then(()=>{mapReady=true;msg("地图已加载，粘贴攻略后即可上图。")}).catch(e=>{const t=e instanceof Error?e.message:"高德地图 SDK 加载失败";$<HTMLElement>("#map-message").textContent=t;$<HTMLElement>("#map-message").hidden=false;msg(t,true)});
